server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      default_schema: public
      hibernate:
        order_by:
          default_null_ordering: last
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        auto_quote_keyword: true
  datasource:
    r2dbc:
      username: postgres
      password: postgres
      host: localhost
      port: 5432
      db-name: pet_shop
  liquibase:
    default-schema: public
    enabled: true
    url: jdbc:postgresql://localhost:5432/pet_shop
    user: postgres
    password: postgres
    change-log: classpath:/changelog/changelog.xml
